### ISSUE TITLE
WebUI Error 502 and no MQTT Entries

### ISSUE THREAD

**Issue by matze19999** [dmslabsbr/hoymiles#112]
Hi,

I just tested your stable and edge addon version and both show no errors in the logs, but also no WebUI and MQTT Entries are available.
The log is in the attachments

[Hoymiles_HASS.log](https://github.com/dmslabsbr/hoymiles/files/11882505/Hoymiles_HASS.log)

I retrieve all MQTT Entries with the command
`mosquitto_sub -v -h homeassistant -p 1883 -t '#'`

**Comment by Cosik** [comment]
Did you try to use MQTT Explorer and wait at least 30 to receive message?

**Comment by matze19999** [comment]
> Did you try to use MQTT Explorer and wait at least 30 to receive message?

Yes, but no messages

**Comment by Cosik** [comment]
Web UI is not implemented. Please enable debug option and send whole logs. In logs there is no problem visible, so it means that problem is on your side. Script is able to connect to mqtt broker.

**Comment by Cosik** [comment]
no response from @matze19999
