### ISSUE TITLE
Which Version to use?

### ISSUE THREAD

**Issue by listiges-kaenguru** [dmslabsbr/hoymiles#122]
Hello and thanks for your great work!

Until today I had the so called "oldStable" in use. Now I tried the "new?" stable an could not find any difference.

I am a little confused by the last changes of the files. Seems like "oldStable" is newer than "stable"?!

Which version do you recommend?

**Comment by Cosik** [comment]
@listiges-kaenguru oldStable is 1.0.8 and stable is 1.1.1 and stable should be newer. On edge we introduce new features. After some time it is transferred to stable. Now it could be a little bit messy because I screw up in releasing last time, so it could be confusing.
