### ISSUE TITLE
Ingress - WebUI - remove button

### ISSUE THREAD

**Issue by bridgewatermedia** [dmslabsbr/hoymiles#126]
I'm not really a developer, but I noticed there are a number of requests or support emails regarding the "WebUI" (ingress) not working.  It has never worked for this, as this doesn't need a UI, but in the config.json it lists:

"services": [
    "mqtt:need"
  ],
  "ingress": true,
  "ingress_port": 5000,
  "host_network": true,
  "panel_icon": "mdi:solar-power",
  "panel_title": "HoyMiles Solar Data Gateway Edge version.",

ingress:true,

Wouldn't it be an easy fix to remove the "WebUI" button by merely changing that to 

ingress:false,

Does this break anything specifically in the rest of the addon?

**Comment by Cosik** [comment]
should be done now

**Comment by bridgewatermedia** [comment]
Works perfect for me. Thanks Cosik.
