### ISSUE TITLE
Second plant

### ISSUE THREAD

**Issue by hangingloose** [dmslabsbr/hoymiles#134]
I use this add on, and I like it!
Now I would like to monitor a second plant.
Reason:
I have two different DTUs.  
For my HM inverter, i bought now a PRO version. 
To get the full feature of the pro, I have to split the plant into two different plants... or i have to buy also the PRO version for my HMT...

Could I connect both plants with home assistant???

**Comment by Cosik** [comment]
@hangingloose it is duplicated by #125
