### ISSUE TITLE
Possibility to customize topic into  MQTT

### ISSUE THREAD

**Issue by guillaume-bzh** [dmslabsbr/hoymiles#151]
Hello,

It could be better if it will be possible to customize topic into MQTT.
Thanks in advance.

Regards,
Guillaume.

**Comment by Cosik** [comment]
Hi,

Sorry now it is impossible. Please read Readme.

**Comment by guillaume-bzh** [comment]
Thanks for your feedback , and the dev of course 🙂
Have a good day !
Guillaume
________________________________
De : Cosik ***@***.***>
Envoyé : lundi 10 juin 2024 18:47
À : dmslabsbr/hoymiles ***@***.***>
Cc : guillaume-bzh ***@***.***>; Author ***@***.***>
Objet : Re: [dmslabsbr/hoymiles] Possibility to customize topic into MQTT (Issue #151)


Hi,

Sorry now it is impossible. Please read Readme.
