### ISSUE TITLE
Add-on HoyMiles Solar Gateway Edge Addon has been remove

### ISSUE THREAD

**Issue by Kwiatjk** [dmslabsbr/hoymiles#173]
Add-on HoyMiles Solar Gateway Edge Addon has been removed from the repository it was installed from. This means it will not get updates, and backups may not be restored correctly as the supervisor may not be able to build/download the resources required.

Clicking submit will uninstall this deprecated add-on. Alternatively, you can check [Home Assistant help](https://www.home-assistant.io/help/) and the [community forum](https://community.home-assistant.io/) for alternatives to migrate to.

**Comment by Cosik** [comment]
![image](https://github.com/user-attachments/assets/1dd5aa8c-e36e-4f1b-a0c6-0693f39a0cf4)
![image](https://github.com/user-attachments/assets/f309cf8d-3d87-4597-8b5c-5bd95b65ff17)

**Comment by Kwiatjk** [comment]
If i set that version will bi problems with encje ?
i lost statatistic etc ?

**Comment by Cosik** [comment]
If you delete them from db you will lost it. Edge was just released to stable...

**Comment by abpei** [comment]
> If i set that version will bi problems with encje ? i lost statatistic etc ?

I stopped and disabled the **Edge** addon, installed the **Stable** addon, added Hoymiles login credentials and started it. It publishes the same entities to the MQTT server so nothing else needs to be reconfigured and everything else keeps working. At least that was the case for me. 

Thanks for all your effort here, Cosik, it is appreciated.

**Comment by Kwiatjk** [comment]
Thx is working

śr., 7 sie 2024, 23:32 użytkownik Aaron ***@***.***> napisał:
