### ISSUE TITLE
MQTT not working after update

### ISSUE THREAD

**Issue by martinhoess** [dmslabsbr/hoymiles#174]
Did the update from 1.1.7 to 1.4.0 and now my entities are missing

![image](https://github.com/user-attachments/assets/f9b2c78a-855c-4193-b10c-8a13a9b809bc)

connection from "outside" works fine
![image](https://github.com/user-attachments/assets/0b3acc29-4ed7-4168-beec-cf73179da3fe)

Restoring to 1.1.7 and everything works fine

**Comment by Cosik** [comment]
Sorry need full logs. I also get confirmation that stable version is working ok.

**Comment by martinhoess** [comment]
[_addon_44349f66_hoymiles_solardata_stable_logs.txt](https://github.com/user-attachments/files/16580706/_addon_44349f66_hoymiles_solardata_stable_logs.txt)

doesn't look like it contains much more (usefull) information

**Comment by Cosik** [comment]
Please try to fully remove addon and install again. It looks like your Broker has problem with generated client_id.

**Comment by martinhoess** [comment]
Nope, same problem after a complete new install 

![image](https://github.com/user-attachments/assets/b4da3a3c-6d70-4888-90de-099ef3d631fd)

If it helps, the MQTT is the one included in the Node Red addon.
But as I said, 1.1.7 worked without any problems

**Comment by martinhoess** [comment]
How long is the generated client identifier? 

![image](https://github.com/user-attachments/assets/f91fc3be-95fb-461a-a26f-ff0dfe3b96f8)

**Comment by Cosik** [comment]
you have your client_id in log file.

**Comment by martinhoess** [comment]
> you have your client_id in log file. It is UUID form python

which is 36 char long ... so it's longer than 23 
has the creation of the client id changed since version 1.1.7?

**Comment by Cosik** [comment]
yes

**Comment by Cosik** [comment]
Hi, I restored uuid generation, but using broker which has such restriction is not a good idea. Also using default user name and password

**Comment by martinhoess** [comment]
> Hi, I restored uuid generation

thank you. 

> but using broker which has such restriction is not a good idea

As I understand it, this is part of the MQTT V3.1 Protocol Specification. This means that any broker who does not follow it has not implemented the protocol according to the specification 🤷‍♂️
With 3.1.x it is even more restricted (only alphanumerical chars are allowed) so the dash in the UUID would also not be allowed
(And yes I have seen the "MAY" part)
![image](https://github.com/user-attachments/assets/9b3b7c1d-8451-48c0-9002-a43b09e72ef6)

> Also using default user name and password

It is within one maschine / one docker environment ... I'm the only person on my network, if someone else should ever be in my network then I have bigger problems than a standard user/pass of an MQTT broker 😉

**Comment by Cosik** [comment]
to be honest I don't know why you are referring to mqtt v3. There is no official information that addon is using this version of protocol. Never the less modern brokers support mqtt v5 which is backward compatible, client ids are not limited. In the future addon will force to use mqtt v5

**Comment by martinhoess** [comment]
> to be honest I don't know why you are referring to mqtt v3. There is no official information that addon is using this version of protocol. Never the less modern brokers support mqtt v5 which is backward compatible, client ids are not limited. In the future addon will force to use mqtt v5

because it does not really matter, MQTT v5 is more or less the same. 
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901059

**Comment by martinhoess** [comment]
With 1.4.1 it works again, problem solved (for now)
