### ISSUE TITLE
ESTAR ENERGY use the same api platform - Make BASE_URL configurable?

### ISSUE THREAD

**Issue by xenio** [dmslabsbr/hoymiles#176]
I have a ESTAR ENERGY Micro Inverter and it use an HERF DCU wifi to connect to the cloud.

Looks like they use the same api platform as Hoymiles.
The website is:
https://monitor.estarpower.com
and api points to:
https://monitor.estarpower.com/platform/api/gateway/

Domain:"monitor.estarpower.com"
Token:
estar_token: (with auth response)
estar_token_language: en_US

Is it possible to have the BASE_URL (and all the necessary url) configurable from the ADDON UI configuration of Home Assistant?

Thanks.

**Comment by Cosik** [comment]
@xenio please check stable from my fork https://github.com/Cosik/hoymiles/tree/master and check if it is working. I added button to switch between estar and hoymiles. If it will not work than it mean there are differences in API.

**Comment by xenio** [comment]
@Cosik thanks, I am not sure if just changing the url is enough, I think the cookie name should be changed too.

COOKIE_UID
https://github.com/dmslabsbr/hoymiles/blob/b1c4e5c4b415b14b5bf08148c5a27451d45059cd/stable/hoymilesapi.py#L355

**Comment by Cosik** [comment]
@xenio did you found another differences? Because without it I will be not able to prepare proper code.

**Comment by xenio** [comment]
I think it is ok, I changed myself url and cookies and it was working, but I can't test it. I switched to OpenDTU, I am not using Herf hardware DCU and the website anymore.

**Comment by Cosik** [comment]
@xenio thanks for info, I think this was the best option. I'm also using OpenDTU
