### ISSUE TITLE
Can not install Edge version in Home Assistant

### ISSUE THREAD

**Issue by MiniPV** [dmslabsbr/hoymiles#178]
I'm very sorry - but how can I install upcoming (developer) Edge Version?

When searching in Add-on Store in can only find:

HoyMiles Solar Gateway oldStable Addon (can not be installed 44349f66_hoymiles_solardata_oldStable)

and

HoyMiles Solar Gateway stable Addon
where version 1.4.1. is installed but not listing all entities (still opened this issue)

That's why I would try it with Edge version - but sorry I'm not able to do it.

Best regards,

Wolfgang from [MiniPV.at]
![hoymiles](https://github.com/user-attachments/assets/0b721af5-9979-4dcd-9eb7-68e2ae6f888d)

**Comment by Cosik** [comment]
Edge was released recently to stable. Edge is rewritten from scratch

**Comment by MiniPV** [comment]
sorry - confused ......

So then I'm still using Edge when installing stable version today?

Best regards,

Wolfgang from MiniPV.at

**Comment by Cosik** [comment]
No, time to time when edge is mature enough it should be released and called stable...
