### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by giacomitti** [dmslabsbr/hoymiles#18]
Hello, I am getting the following error when trying to installing it:

21-07-02 10:06:00 INFO (SyncWorker_3) [supervisor.docker.addon] Starting build for 44349f66/amd64-addon-hoymiles_solardata:0.19
21-07-02 10:06:03 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build 44349f66/amd64-addon-hoymiles_solardata:0.19: manifest for homeassistant/amd64-base-python:3.9-alpine3.122 not found: manifest unknown: manifest unknown
21-07-02 10:06:03 ERROR (SyncWorker_3) [supervisor.docker.addon] Build log: 
Step 1/21 : ARG BUILD_FROM=homeassistant/amd64-base-python:3.7-alpine3.12
Step 2/21 : FROM $BUILD_FROM

**Comment by dmslabsbr** [comment]
Sorry, but i did everything based on the raspberry pi ARM architecture. That could be it.

I'll look later.

**Comment by hstern** [comment]
I, too, have the same issue installing on hassio/linux amd64.

**Comment by hstern** [comment]
I think it's just a typo. See #20

**Comment by dmslabsbr** [comment]
I just update. Thank you!
