### ISSUE TITLE
After a restart of Home Assistant no data received

### ISSUE THREAD

**Issue by Wind06** [dmslabsbr/hoymiles#183]
Hello,

Since some times when performing a Home Assistant restart, let say after having installed an update.
I have to restart the hoymiles solar otherwise no update of data occured... is this a known issue ?

PS: If you need testing help for the edge version, I am ready to help

**Comment by Cosik** [comment]
@Wind06 data is send every 8 minutes so it will take some time. But if you restart also broker it could be a problem that addon is not reconnecting to the mqtt broker.

**Comment by Wind06** [comment]
@Cosik, understood, thanks for your answer. In my case when I restart HAS the mqtt broker is also restarted, thats's the reason why :-)
