### ISSUE TITLE
Error wrong user/password

### ISSUE THREAD

**Issue by tom9865** [dmslabsbr/hoymiles#186]
hi,

Thanks for the work!!!

I installed everything and configured. Still always receiving this Error:

HoymilesAdd-on.hoymilesapi.Hoymiles - ERROR - Wrong user/password

+ one for can't get accedd token.

Any ideas/solutions on this? Login with same data on global.hoyniles/cloud works with no problem.

BR,
Tom

**Comment by Cosik** [comment]
did you will correct data in configuration? If you don't get access it mean that your credentials are not correct.

**Comment by tom9865** [comment]
Thanks! I re-installed the plugin again. Somehow the config got lost another two times - now it is working ;)
