### ISSUE TITLE
HoyMiles Solar Data no visible as data source for the new Energy dashboard (HA 2021.8.1)

### ISSUE THREAD

**Issue by Papi77** [dmslabsbr/hoymiles#19]
Hi,
As Home Assistant 2021.8.1 just released their support for Energy management I am trying to use the Hoymiles solar data gateway as source for the "Return to Grid" part of the setup. However, there are "No matching statistics" found message.

Is it possible to use this Add-On as an Integration to allow to be used with Energy dashboard?

Regards,
Pawel

**Comment by dmslabsbr** [comment]
Hi, I didn't try it yet.   I soon look it. 

Thank you.

**Comment by brzozow** [comment]
Hi @dmslabsbr . Thanks for plugin. I'm using it and it would be great to add support for Energy management.

To use HoyMiles add-in in Energy management you should  add following attributes:
state_class: measurement
last_reset: (time or last reset).
It should be added to month_eq, today_eq and total_eq
It can be tricky to calculate last_reset for month_eq and today_eq (should it be reset at midnight or when values drop to zero)?

BTW: I noticed that for today_eq sensor unit_of_measurement attribute is set to kWh. In my case in today_eq I have value in Wh.
Best regards,
Michal

**Comment by Papi77** [comment]
To add to above requirements: would it be possible to provide total_eq in kWh (so that we don’t have to reset it at all and yet use it foe Energy dashboard)?

**Comment by Krzysztonek** [comment]
> 
> 
> Hi @dmslabsbr . Thanks for plugin. I'm using it and it would be great to add support for Energy management.
> 
> To use HoyMiles add-in in Energy management you should add following attributes:
> state_class: measurement
> last_reset: (time or last reset).
> It should be added to month_eq, today_eq and total_eq
> It can be tricky to calculate last_reset for month_eq and today_eq (should it be reset at midnight or when values drop to zero)?
> 
> BTW: I noticed that for today_eq sensor unit_of_measurement attribute is set to kWh. In my case in today_eq I have value in Wh.
> Best regards,
> Michal

Hi there,

To convert any measurements from one unit to another, you can do some recalculation on your own.
Please see how I did this for my own hoymiles solar farm:

![obraz](https://user-images.githubusercontent.com/87784133/132940002-da58503f-83d1-4671-b16f-712d36a38973.png)

**Comment by Krzysztonek** [comment]
> 
> 
> Hi @dmslabsbr . Thanks for plugin. I'm using it and it would be great to add support for Energy management.
> 
> To use HoyMiles add-in in Energy management you should add following attributes:
> state_class: measurement
> last_reset: (time or last reset).
> It should be added to month_eq, today_eq and total_eq
> It can be tricky to calculate last_reset for month_eq and today_eq (should it be reset at midnight or when values drop to zero)?

Yes, adding full support to the HA Energy Management would be really great and very useful.

@dmslabsbr , I would also kindly suggest adding long-term statistics if possible, to integrate your solution with the Energy Management add-on.

**Anyway, you did a great job so far! Thank you so much!** 😄  👍

**Comment by dmslabsbr** [comment]
Thank everybody for your comments.

I'm a bit busy in these days.  But I will put these suggestions in my add-on.

**Comment by dmslabsbr** [comment]
Hi, I just upload a new add-on version. 

If anyone could try, it will be good!

I know that it need some adjustments.

**Comment by maakuth** [comment]
I've tried it and it does not seem to be quite correct, even though the new values show up in the energy configuration. Now the real_power value is duplicated to three fields, some of which show up in the energy settings, but they are all getting the same value. That value was earlier in watts, which was correct - now it is in kilowatt hours. I think correct thing to do would be to add the last_reset information to total_eq and change the unit there to MWh, And then the new real_power fields could be removed and the remaining one reverted to W instead of kWh.

**Comment by dmslabsbr** [comment]
@maakuth , Hi!  Thank you for your comments.

I replicate real_power to test some different configurations. I'm look closer yours suggestions.

**Comment by maakuth** [comment]
Thank you for the effort! I will test it once you push something. It is possible that I can contribute some changes myself.

**Comment by maakuth** [comment]
I've been running the new version for a few weeks. The solar production variables can be selected in the "Configure solar panels" dialog, but nothing appears in the statistics, unfortunately.

**Comment by maakuth** [comment]
Actually it does work now! I don't quite understand why, but it's nice :+1: 

![image](https://user-images.githubusercontent.com/750973/140273258-e2b70121-ebee-4dc9-857d-4c3641d11fd6.png)

**Comment by dmslabsbr** [comment]
Ok!
