### ISSUE TITLE
Addon restart is required after restarting Core

### ISSUE THREAD

**Issue by gralin** [dmslabsbr/hoymiles#24]
If we restart Core, this addon also need to be restarted to continue working. Would be great if this addon could recover from such situation on it's own without having to be restarted.

**Comment by dmslabsbr** [comment]
This is new to me!

I'm going to look it.  Thank you for your comment.

**Comment by dmslabsbr** [comment]
Hi, have you tried to enable the add-on plug-in Watchdog ?

**Comment by gralin** [comment]
Unfortunately I tried that and doesn't help. The add-on doesn't crash, I can still access the web ui, but the sensors become unavailable until I restart the add-on. 
![image](https://user-images.githubusercontent.com/3457048/135355650-b73c5a14-f176-4888-96a6-14aa013df5f2.png)

**Comment by kucinskimarek** [comment]
In v. 0.24.1 it keeps happening. 
After restart HA addon starts itself (log's are OK) but sensors are unavailable until restart the addon again in Supervisor.

**Comment by Cosik** [comment]
Due to specific working of addon I don't know how to detect reset of HA. Also sending data in shorter period is imo out of sense because values on cloud are updated in 15 min period.

**Comment by kucinskimarek** [comment]
Hmm...
Until today I was sure that restarting HA causes all addons to restart at the same time, so I thought it was a bug in the add-on
