### ISSUE TITLE
Sensor unavailable

### ISSUE THREAD

**Issue by walberjunior** [dmslabsbr/hoymiles#25]
Hi.

Sensors often appear as unavailable, but when accessing via the "OPEN WEB UI" the information is ok.
I need to press rebuild or restart, but it doesn't always work.

Thanks for the add-on
![HoyMiles_2](https://user-images.githubusercontent.com/20650850/133867067-0cd13d3f-35d2-44ff-9050-54670e54434a.jpg)
![HoyMiles_1](https://user-images.githubusercontent.com/20650850/133867071-55374148-3511-47e4-b559-88ff21330142.jpg)

**Comment by dmslabsbr** [comment]
Hi, thank you for your comment.  

I'm already looking for it.  The problem already related in https://github.com/dmslabsbr/hoymiles/issues/24

I hope soon this bug going to fixed.
