### ISSUE TITLE
Failed to update to v. 0.20d BETA in HA

### ISSUE THREAD

**Issue by kucinskimarek** [dmslabsbr/hoymiles#27]
Hi,
When I try to update add-on in HA I get error:

![image](https://user-images.githubusercontent.com/78976766/135399407-9743cfd2-94d3-4895-b3cd-5bba5b3879c9.png)

**Comment by tonwelle** [comment]
Same here, even when reinstalling the adding from scratch. Same error message.

**Comment by dmslabsbr** [comment]
I'm receiving the same message.  I'm trying to fix it.  Thank you for your comments.

**Comment by dmslabsbr** [comment]
Hi, I made some adjustments and I think the bug is gone.

**Comment by Krzysztonek** [comment]
Confirmed, the bug has gone. :)
I'd love also to confirm that DTU Mi model also fully works with this add-on.
![DTU-MI-HOYMILES](https://user-images.githubusercontent.com/87784133/135680429-d50f6fd4-2917-4901-8fe1-8963d2c43ccc.png)
.
