### ISSUE TITLE
More then One Solar plant

### ISSUE THREAD

**Issue by Kwiatjk** [dmslabsbr/hoymiles#37]
Hi, 
I have more than one solar plant , its possible monitoring more than one ?

**Comment by dmslabsbr** [comment]
This option is not currently in the code.

Maybe if you run two instances of the add-on you will be able to monitor two solar plants simultaneously.

For example, clone this repository and add the new repository to your home assistant. So you should be able to run more than one instance of the add-on.

Thanks for the comments.

**Comment by dmslabsbr** [comment]
Hi, could you help with some $ ?

**Comment by Cosik** [comment]
@Kwiatjk probably it will be possible when I will finish refactor of code. How do you expect that this will works? For example automatic read all available plants?

**Comment by Kwiatjk** [comment]
Hi,
I think the best option will be + add new plant

**Comment by Cosik** [comment]
Hi, sorry for delay. @Kwiatjk please test edge version 1.0.12. It support multi plants, should be separate by , in configuration. I tested it with double set the same plant ID. First please test it with 2 plants and give me info after about 1h of running if mqtt is logging correctly.

**Comment by Kwiatjk** [comment]
Hi
Will check

**Comment by Cosik** [comment]
Any update?

**Comment by Kwiatjk** [comment]
No, not yet. I don't have time , sorry

**Comment by Cosik** [comment]
No response for a long time. I'm closing ticket.
