### ISSUE TITLE
After upgrade to 0.22a7 cannot start Add-on

### ISSUE THREAD

**Issue by Papi77** [dmslabsbr/hoymiles#45]
The 0.22a7 version causes the add-on to fail to start. 
Error only says: expected int
 
FAILED TO START ADD-ON - CONFIGURATION VALIDATION FAILED

Supervisor entry:
22-01-19 07:23:37 ERROR (MainThread) [supervisor.addons.addon] Add-on 44349f66_hoymiles_solardata has invalid options: expected int. Got {'HOYMILES_USER': 'xxx', 'HOYMILES_PASSWORD': 'Xxx', 'HOYMILES_PLANT_ID': 'xxx', 'DEVELOPERS_MODE': False, 'External_MQTT_Server': False, 'External_MQTT_Host': '127.0.0.1', 'External_MQTT_User': 'nda', 'External_MQTT_Pass': 'nda', 'External_MQTT_TLS': False, 'External_MQTT_TLS_PORT': 'nda'}

**Comment by jgrobelny-dev** [comment]
Check issue #44 . It solved my issue

**Comment by Papi77** [comment]
Thanks! That did help!

**Comment by dmslabsbr** [comment]
Already repported - issue #44
