### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Cosik** [dmslabsbr/hoymiles#52]
Readme has to be updated due to changes, and should contain full instruction of install and config.

**Comment by Cosik** [comment]
@DavidW250 maybe you could support updating and developing main project repo?

**Comment by DavidW250** [comment]
At somepoint, yes, but I'm new to Git, new to Github, new to Home Assistant and just learning to program, so I have a lot to figure out before I am likely to be helpful.

**Comment by Cosik** [comment]
But programming is not only thing in which we need help, also translation and etc. Now I'm start to rewriting whole code and implement clean code practices. Also testing is very important.
