### ISSUE TITLE
Wrong data in sensor.solarH_xxxxx_total_eq at 0,24 rev

### ISSUE THREAD

**Issue by Chris125913** [dmslabsbr/hoymiles#57]
My data is in the pic below. Do you have the same issue?

![hoymiles entity](https://user-images.githubusercontent.com/69140260/156158786-29239929-334d-4612-b69c-ce034846dce7.png)

it is more than 4 GWh :-)

As I see it is a problem with a unit of measure. 

PS 
To all contributors - many thanks, good job,

**Comment by Cosik** [comment]
Strange on my side is correct, I also checked code and all values are default in Wh and then divided by 1000. 

![plant](https://user-images.githubusercontent.com/1255379/156160498-cd7a08f6-ffb2-427c-9864-c4c47807dca4.jpg)


When you perform update?

**Comment by Chris125913** [comment]
As I remember it was yesterday after 5 PM. Today I'm reinstalling the Add-on and no chances.

**Comment by Cosik** [comment]
Please check now.

**Comment by Chris125913** [comment]
HI. I was updating hoymiles.py but no changes. After that, I deinstall and install the add-on and now total_eq is show data ok. 
BTW Should I expect value year_eq but I can't find this
Why, becouse I find line in hoymiles.py
solar_data['total_eq'] = str( round(float(solar_data['total_eq']) / 1000,2) )
and this line was changed to
solar_data['year_eq'] = str( round(float(solar_data['total_eq']) / 1000,2) )

**Comment by Cosik** [comment]
Did you update it after my change? How you updated it? Maybe try uninstall it and then install it? To be honest I don't know how to provide hot fixes. I will try bump version.

**Comment by Chris125913** [comment]
version 0.24.1 works good
