### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by bridgewatermedia** [dmslabsbr/hoymiles#58]
This could just be me as I'm very new to Home Assistant and MQTT but the Dashboard link on the left has never worked for me.  It constantly gives an error 502:Bad Gateway.  What is this supposed to look like?  I can get data out and display it in LoveLace, but that sidebar menu doesn't do anything.  Also - what is the 'simple web interface' all about? I'd be happy to help with the documentation about how to install if I knew myself how to do so.  I've provided a bunch of screenshots to show my settings.  

![solar1](https://user-images.githubusercontent.com/97800204/156417390-84bd3085-467a-44d7-9608-813d66250c50.jpg)

![solar2](https://user-images.githubusercontent.com/97800204/156417401-71217bc4-3c62-468c-ba41-43298738760c.jpg)

**Comment by Cosik** [comment]
#56 was disabled due too pour quality and need re implementation in python. Probably will be not enabled before version 1.x

**Comment by dmslabsbr** [comment]
improvement @ #47
