### ISSUE TITLE
Warnings in Log

### ISSUE THREAD

**Issue by bridgewatermedia** [dmslabsbr/hoymiles#59]
Just a warning, but I thought I'd post this here in case it is related to something else.

![image](https://user-images.githubusercontent.com/97800204/156561707-ad0e98c8-149b-4cbd-a8c0-023cae8ae1ad.png)

**Comment by Cosik** [comment]
If I good remember watch dog is not implemented, correct @dmslabsbr

**Comment by kucinskimarek** [comment]
Hi,
In addition to the ones listed above which also occur to me, I have these warnings:

![prtscr](https://user-images.githubusercontent.com/78976766/156577297-a2df4d4d-9f6c-4018-afe2-68189c673c83.JPG)

**Comment by Cosik** [comment]
@kucinskimarek please reinstall plugin and restart HA. There were changes in main json file.

**Comment by Cosik** [comment]
@kucinskimarek not implemented watchdog will cause restart of addon even if it not hangup

**Comment by kucinskimarek** [comment]
@Cosik I got it, thanks.
In that case, I will update the original issue on this.

**Comment by dmslabsbr** [comment]
> If I good remember watch dog is not implemented, correct @dmslabsbr ?

Yes. It not implemented yet. 

Thank you!
