### ISSUE TITLE
Connection refused. App EXIT

### ISSUE THREAD

**Issue by Krzysztonek** [dmslabsbr/hoymiles#60]
Dear @dmslabsbr 

After last add-on update I faced following issue:

![image](https://user-images.githubusercontent.com/87784133/156640115-e1271247-cc81-40e5-ad08-1cee0ce4db2c.png)

Could you please, advise?

**Comment by Cosik** [comment]
Did you fill mqtt IP, user and password?

**Comment by dmslabsbr** [comment]
Do you use a internal mqtt or a external mqtt server?

> Dear @dmslabsbr
> 
> After last add-on update I faced following issue:
> 
> ![image](https://user-images.githubusercontent.com/87784133/156640115-e1271247-cc81-40e5-ad08-1cee0ce4db2c.png)
> 
> Could you please, advise?

**Comment by Krzysztonek** [comment]
@dmslabsbr ,
I'm using MQTT Mosquitto Broker only:

![image](https://user-images.githubusercontent.com/87784133/156664474-5598d50f-f7a1-4656-bd99-4c139eb89f80.png)

with the following credentials (dedicated `hoymiles` user already created):

![image](https://user-images.githubusercontent.com/87784133/156664185-ff6f3a8a-4a15-4376-b98d-a7aa9f621a44.png)

**Comment by dmslabsbr** [comment]
There is a bug when add-on is getting internal mqtt host, user and password.
We will fix it.
Thank you.

**Comment by dmslabsbr** [comment]
@Cosik , I just upload a correction for bug of issue #60 . https://github.com/dmslabsbr/hoymiles/tree/issue60. - Could you check it?

**Comment by Cosik** [comment]
@dmslabsbr looks good, better than previous solution ;)

**Comment by Cosik** [comment]
Yes, please do it :)

**Comment by Cosik** [comment]
@dmslabsbr when you will implement this fix, please also fix version of stable. I srew up somehow preparing edge version and stable verison is now 1.0 instead of 2.4.x

**Comment by dmslabsbr** [comment]
@Cosik , 0.24 wouldn't just be the oldStable version?

Maybe I didn't understand well.
