### ISSUE TITLE
Split code - stable + dev

### ISSUE THREAD

**Issue by dmslabsbr** [dmslabsbr/hoymiles#61]
Split the add-on code into two folders like stable and dev.

Create a new repository.json for each folder.
or make something like https://github.com/dmslabsbr/hass-addons

**Comment by Cosik** [comment]
@dmslabsbr currently developement I'm doing on dev branch. Also I was looking for some solution how to introduce for example odlstable. But due to information in email from you, I need to change release 1.x and there will be no change in entities naming. Only new will be added.

**Comment by Cosik** [comment]
Ok, I found how we could do it , like here https://github.com/home-assistant/addons when you think that we could do it? Before release 1.0?

**Comment by dmslabsbr** [comment]
@Cosik, I think that it be a good idea.

Because some people already use the beta versions. And they may not like having new bugs. Although this is good for testing

I suggest for now something like that:

<img width="262" alt="Captura de Tela 2022-03-04 às 15 01 14" src="https://user-images.githubusercontent.com/3632067/156817422-f096bf40-1fc8-41ce-84e0-f4befb13084b.png">

and when the 1st stable new version, the folders goes something like that.

<img width="254" alt="Captura de Tela 2022-03-04 às 15 02 11" src="https://user-images.githubusercontent.com/3632067/156817557-d5d05f10-a07e-4cc4-b681-002f40e72267.png">

I tried to add on home assistant add-on a different github branch than master, but i could'nt. 

so, when user add https://github.com/dmslabsbr/hoymiles in your add-ons painnel, they will see two options to instal... the old-stable and last-edge-version.


> Ok, I found how we could do it , like here https://github.com/home-assistant/addons when you think that we could do it? Before release 1.0?

**Comment by Cosik** [comment]
Will you have time to prepare it?

**Comment by dmslabsbr** [comment]
In this weekend. 
    Em sexta-feira, 4 de março de 2022 15:46:14 BRT, Cosik ***@***.***> escreveu:  
 
 


Will you have time to prepare it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dmslabsbr** [comment]
Ok. OldStable folder is working.

<img width="822" alt="Captura de Tela 2022-03-06 às 13 12 38" src="https://user-images.githubusercontent.com/3632067/156931499-0639d588-bd3f-41ce-b3da-9ef9ef5428e8.png">

**Comment by Cosik** [comment]
@dmslabsbr I think that also files in root repo folder should be removed, or moved to stable dir. Or we let it as it is?
