### ISSUE TITLE
UTF-8 character encoding is missing

### ISSUE THREAD

**Issue by llcoolmm** [dmslabsbr/hoymiles#63]
Hey,
UTF-8 character encoding is missing.

 File "/usr/local/lib/python3.9/http/client.py", line 168, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0144' in position 199: Body ('ń') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.

**Comment by Cosik** [comment]
Please send full log.

**Comment by llcoolmm** [comment]
It was old stable version. 

thanks
