### ISSUE TITLE
Old Stable version uninstalling issue

### ISSUE THREAD

**Issue by Krzysztonek** [dmslabsbr/hoymiles#73]
Dear @dmslabsbr ,

To install a brand new add-on version I tried to uninstall the obsolete old version. However, after executing this process I'm still able to see this add-on on a HASSIO dashboard:

![image](https://user-images.githubusercontent.com/87784133/158991037-a7a2add2-99d9-46f2-8bb9-182a69da91b2.png)

When clicking this add-on it reports as UNINSTALLED (INSTALL prompt appears):

![image](https://user-images.githubusercontent.com/87784133/158992104-61613d93-b2b0-4ae2-8eb7-d28fd2633468.png)

...but it still remains visible on a dashboard, even if it is not yet installed back.
Before installing a new version I need to completely remove the obsolete one, right?
Please kindly advise how to do it?

**Comment by Cosik** [comment]
Did you try ctrl+F5?

**Comment by Krzysztonek** [comment]
Hi @Cosik ,
Yes, I've just tried ctrl+F5 and... it helped! Thank you!
The obsolete version has been replaced with a new 1.0.4 version.
I have configured it with my credentials as per requirements and indicated the internal Mosquitto MQTT server.

![image](https://user-images.githubusercontent.com/87784133/158995562-c770844a-b580-4274-a6c8-ec147b25e5f7.png)

Then, when trying to open a web IU of this newly installed add-on, the screen shows nothing more that that:

![image](https://user-images.githubusercontent.com/87784133/158994493-a4455139-4872-4f2c-bf0b-ddd2a128edae.png)

Here is my log:

![image](https://user-images.githubusercontent.com/87784133/158996400-05af1b3e-fb49-4eca-97f3-deccf0c217ad.png)

What am I doing wrongly?

**Comment by Cosik** [comment]
Web UI was disabled.

**Comment by Krzysztonek** [comment]
So, how to enable it?
The button is accessible:
![image](https://user-images.githubusercontent.com/87784133/158997844-252309b9-31b5-4526-8e3d-cd264e45800f.png)

**Comment by Cosik** [comment]
Was disabled in code. Button was not removed. Sorry.

**Comment by Krzysztonek** [comment]
Now it's clear. Thank you! :)
