### ISSUE TITLE
Any chance to make this a HACS integration?

### ISSUE THREAD

**Issue by eduspina** [dmslabsbr/hoymiles#76]
Hi there,

First of all, thanks for all your hard work on this add-on!!!

Is there any chance to make this add-on a HACS integration? For the ones, that like me, runs Home Assistant on a docker, it is impossible to use this add-on as we don't have the supervisor.

Thanks and sorry if this is not the right place to ask for it.

**Comment by dmslabsbr** [comment]
It's a good idea, it's not a priority right now but we'll keep it noted for future use.

But, 

You can use this app in another docker container.
Just need to understand a little bit of python, docker and make some changes.

Create a new docker image with oldStable files., maybe you need to clone https://github.com/dmslabsbr/hoymiles/tree/master/oldStable,

 You need to install: https://github.com/eclipse/paho.mqtt.python and https://github.com/psf/requests in your new docker container.

You need to change .../oldStable/Dockerfile  and configure ../oldStable/secrets.ini with your mqtt server data.

There are some jobs and searches to do, but it will work.

**Comment by eduspina** [comment]
Awesome!!!

Thanks Daniel, it worked... I had to tweak a few more things but it seems it is working!!!

![image](https://user-images.githubusercontent.com/87581664/168903824-f306e693-069f-4b37-bce2-4567441bee71.png)

Great job and keep up with the project!!! ;)

**Comment by dmslabsbr** [comment]
Great!  
Thank you for your feedback.
