### ISSUE TITLE
Data loss, or untrusted? Abnormal computing behaviour

### ISSUE THREAD

**Issue by Krzysztonek** [dmslabsbr/hoymiles#83]
Hi,
Energy data comparison functionality appeared in 2022.6 Core version. However, when trying to compare year-to-year energy production data, or displaying a yearly production only, I see a NEGATIVE value:

![image](https://user-images.githubusercontent.com/87784133/172151641-71374015-d3c4-4422-a3a9-99a8216d53eb.png)

Please advise what to do to get the correct data. How to reset all the data and start gathering them from scratch?

**Comment by Cosik** [comment]
How to reset (if we are talking about HA):
1. Delete database file - this will cause lost of all data even other than solar.
2. Edit data base - remove records related to solar data.
