### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by danMy74** [dmslabsbr/hoymiles#87]
Hi, I have the problem that "502: Bad Gateway" is displayed in the UI, I don't see the data in the dashboard. No errors appear in the log.

Thanks in advance

**Comment by danMy74** [comment]
So now I can see the data in the dashboard but the UI still doesn't work

**Comment by Cosik** [comment]
First at all, as usually we have to use magic ball to guess what you have. Also I have no idea to which UI you reefer. This add-on has no UI, only configuration.

**Comment by danMy74** [comment]
![Bild_2022-07-24_120654252](https://user-images.githubusercontent.com/98981198/180642191-701cc624-73f6-4375-a09d-d65dddd5ffaf.png)


I mean this UI

**Comment by Cosik** [comment]
#56 #86

**Comment by danMy74** [comment]
Thanks :D
