### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by srspereira** [dmslabsbr/hoymiles#92]
hi guys... I'm getting 502, also none entities were created. 

exploring mqtt: 
homeassistant/binary_sensors/dmslab/solarH_[id from device list] are all created: 
 i.e:  
 {"stat_t": "home/solar/json_2878710", "name": "solarH_2878710_connect", "uniq_id": "solarH_2878710_connect", "val_tpl": "{{ value_json.connect }}", "icon": "mdi:solar-panel", "device_class": "connectivity", "device": {"name": "Hoymiles Gateway", "manufacturer": "Hoymiles", "model": "None", "sw_version": "", "via_device": "2878710", "identifiers": ["solarH_2878710"]}}

same for sensors:
 i.e.: 
  {"stat_t": "home/solar/json_631960", "name": "solarH_631960_today_eq", "uniq_id": "solarH_631960_today_eq", "val_tpl": "{{ value_json.today_eq }}", "device_class": "energy", "state_class": "total_increasing", "unit_of_measurement": "kWh", "expire_after": "720", "device": {"name": "Hoymiles Gateway", "manufacturer": "dmslabs", "model": "Hoymiles add-on", "sw_version": "1.0.7", "via_device": "631960", "identifiers": ["solarH_631960"]}}

/home/solar/json_631960 [ I'm assunig this is my dtu id]:
{"today_eq": "42.25", "month_eq": "160.48", "year_eq": "160.48", "total_eq": "160.48", "real_power": "11000.0", "co2_emission_reduction": "0.16", "plant_tree": "8.744", "data_time": "2022-10-27 11:49:17", "last_data_time": "2022-10-27T11:49:17-03:00", "capacitor": "14400.0", "is_balance": 0, "is_reflux": 0, "reflux_station_data": null, "real_power_measurement": "11000.0", "real_power_total_increasing": "11000.0", "power_ratio": "76.4", "capacitor_kW": "14.4", "today_eq_Wh": "42251.0"}

attached log
[hoymiles.log](https://github.com/dmslabsbr/hoymiles/files/9880554/hoymiles.log)

valeu!

**Comment by Cosik** [comment]
#89 #87
