### ISSUE TITLE
#92

### ISSUE THREAD

**Issue by srspereira** [dmslabsbr/hoymiles#93]
full logs are attached... 
-- and YES 502 is not showing in the logs -- that's a ingress error ( where can I find the log of 502 of this add-on ? )

![Captura de Tela 2022-10-27 às 13 22 23](https://user-images.githubusercontent.com/20144831/198345439-f5c20572-0a5c-4af8-9760-f89994a0527a.png)

add-on are creating all MQTT messsages -- but not creating the entities ( binary sensors and so on),
please let me know if this add-on do not create those entities.

![Captura de Tela 2022-10-27 às 13 22 23](https://user-images.githubusercontent.com/20144831/198345439-f5c20572-0a5c-4af8-9760-f89994a0527a.png)

        #89 #87

Missing full logs and details what has been used, also in log there is no 502

_Originally posted by @Cosik in https://github.com/dmslabsbr/hoymiles/issues/92#issuecomment-1293759222_

**Comment by Cosik** [comment]
Why you created another issue without full meaning topic? I looked in to the log and it is not full, there is missing beginning of the addon execution. This addon is not creating any entities, devices etc. HA with broker are responsible of if. Still I don't know what you are showing. Addon is not providing any dashboard/web page it was mentioned in linked issues.

**Comment by srspereira** [comment]
my  mistake.. but thanks for information because on documentation it's misleading regarding entities -- because show entities created [ a single line on documentation with you reply : "This addon is not creating any entities, devices etc. HA with broker are responsible of if." )  
2nd issue and that's what leading to so many 502 issues is this add-on do not have any web interface  but has 
"open web ui" and  "show in sidebar" toogle.. 

 

![image](https://user-images.githubusercontent.com/20144831/198347332-db7906d8-69ae-426f-82a6-851ccc79bc23.png)

**Comment by Cosik** [comment]
In my opinion this line shouldn't be in documentation, this only mean that you don't know how mqtt is working on Home Assistant. What is more I mentioned that you were not provided full log so I didn't know what you are using, also this information was included in linked issues and described, ui was disable on current stable and edge version.

**Comment by srspereira** [comment]
--- 1st I do know how mqtt works. 
--- 2nd... I was using the stable
--- 3rd..  ui is disable BUT not on add-on -- check it first..  

--- e em bom portugues..  dane-se

**Comment by Cosik** [comment]
So if you see room for improvement please don't hesitate and propose some pull request with improvements.


PS. I also know different languages.
